### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jimchen5209** [OKTW-Network/en#12]
To Translate:

- [ ] Chunkloader
- [ ] ht-ct
- [ ] News
- [ ] Teleporter(https://github.com/OKTW-Network/oktw-network.github.io/pull/14)
- [ ] Materials(https://github.com/OKTW-Network/oktw-network.github.io/pull/14)
- [ ] Upgrades(https://github.com/OKTW-Network/oktw-network.github.io/pull/14)

To Merge from Chinese

- [ ] New Categories(https://github.com/OKTW-Network/oktw-network.github.io/pull/14)
